name: color_map
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  vector_math: ^2.1.4
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  csv: ^5.0.2
