name: color_map
description: Colormaps for Dart/Flutter imported from Matplotlib.colormaps.
version: 1.0.0
homepage: https://github.com/organic-nailer/color_map_dart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  vector_math: ^2.1.4
  

dev_dependencies:
  lints: ">=2.0.0 <4.0.0"
  test: ^1.21.0
  csv: ^5.0.2
